name: Dependabot auto-approve
on: pull_request

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependabot:
    name: "Auto-approve Dependabot PRs"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # to allow the Action to approve PRs
    # Checking the author will prevent your Action run failing on non-Dependabot PRs
    # Checking the repository will prevent your Action run happening on forked repos
    if: ${{ (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'pre-commit-ci[bot]') && github.repository == 'ansys/openapi-common' }}
    steps:
      - name: "Approve a PR if not already approved"
        run: |
          FILTER=".[] | select(.number==$EVENT_NUMBER).reviewDecision"
          PR_STATUS="$(gh pr list --repo $REPOSITORY --json 'author,number,reviewDecision' -q "$FILTER")"
          if [ $PR_STATUS == "REVIEW_REQUIRED" ]; then
            gh pr review --approve "$PR_URL"
          else
            echo "PR status set to $PR_STATUS. Not approving."
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPOSITORY: ${{ github.repository }}
          EVENT_NUMBER: ${{ github.event.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
